# Generated by Django 6.0.2 on 2026-02-12 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_benefittype_location_person_referrerorganization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
            ],
            options={
                'verbose_name': 'Medewerker',
                'verbose_name_plural': 'Medewerkers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.person',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Studenten',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.person',),
        ),
    ]
