# Generated by Django 6.0.2 on 2026-02-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Nog beginnen'), ('active', 'Actief'), ('dropped', 'Afgevallen'), ('completed', 'Afgerond')], default='pending', max_length=20),
        ),
    ]
