# Generated by Django 6.0.2 on 2026-02-12 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_studentprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_type', models.CharField(choices=[('uwv', 'UWV'), ('municipality', 'Gemeente'), ('other', 'Overige organisatie')], max_length=20)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='referrer_org',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organization'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organization'),
        ),
        migrations.DeleteModel(
            name='ReferrerOrganization',
        ),
    ]
