# Generated by Django 6.0.2 on 2026-02-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_organization_remove_studentprofile_referrer_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('municipality', 'Gemeente'), ('other', 'Overige organisatie')], max_length=20),
        ),
    ]
