# Generated by Django 6.0.2 on 2026-02-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_organization_org_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('org_type', 'name')},
        ),
    ]
