# Generated by Django 6.0.2 on 2026-02-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_organization_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together=set(),
        ),
    ]
