# Generated by Django 6.0.2 on 2026-02-14 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_signalcategory_signal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='active_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
