# Generated by Django 6.0.2 on 2026-02-18 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_signalhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('mon_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('tue_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('wed_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('thu_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('fri_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('sat_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('sun_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='core.person')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.workpackage')),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RosterDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('work', 'Werken'), ('sick', 'Ziek'), ('vacation', 'Vakantie'), ('off', 'Vrij'), ('swapped', 'Geruild'), ('absent', 'Ongeoorloofd afwezig'), ('other', 'Anders')], default='work', max_length=20)),
                ('planned_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_days', to='core.person')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('person', 'date'), name='uniq_person_date_rosterday')],
            },
        ),
        migrations.CreateModel(
            name='RosterDayWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_work', to='core.person')),
                ('work_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workpackage')),
            ],
            options={
                'ordering': ['date', 'work_package__sort_order', 'work_package__code'],
                'constraints': [models.UniqueConstraint(fields=('person', 'date', 'work_package'), name='uniq_person_date_wp')],
            },
        ),
    ]
